### ISSUE TITLE
Add custom `print` layout CSS rules

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-rb.github.io#18]
Add custom print CSS rules to make the web pages print nicer. The top `nav` links should probably be hidden. The SVG images on the front page should also probably be hidden or resized to be smaller?

**Comment by s-vamshi** [comment]
@postmodern I would like to work on this issue

**Comment by postmodern** [comment]
@s-vamshi feel free to start working on this. As you can probably see by doing a Print Preview, the website doesn't render correctly in the print layout.

Note: I don't assign issues to new contributors, because every time I have done that in the past they have disappeared and the issue never got completed.

**Comment by s-vamshi** [comment]
@postmodern sure started working on it, I have checked the print preview for every route, here are the things I have noticed
1. On landing page which is https://ronin-rb.dev/ print preview isn't working.
2. In /blog route only nav bar and logo are visible
3. In all over pages thought of adding margins to page and reducing logo size and hiding nav bar on print

**Comment by s-vamshi** [comment]
@postmodern are footer links necessary to be shown on print?

**Comment by postmodern** [comment]
> @postmodern are footer links necessary to be shown on print? Because they are taking lot a space vertically.

I would say no, because they are meant to help with navigation. It's not necessary to include them in the print view for every page.

**Comment by postmodern** [comment]
> @postmodern sure started working on it, I have checked the print preview for every route, here are the things I have noticed
> 
> 1. In /blog route only nav bar and logo are visible
> 2. In all over pages thought of adding margins to page and reducing logo size and hiding nav bar on print

Adding to this analysis. Here's a PDF of the index page generated by Chrome.

1. It took forever to load and render the Print Preview for some reason. I'm guessing because of the animated SVGs.
2. The social media link icons at the bottom of the page end up taking up whole individual pages.
3. Top-nav bar and footer links should probably be hidden.
4. Inconsistent page breaks for content.
[ronin_print_preview.pdf](https://github.com/ronin-rb/ronin-rb.github.io/files/12826057/ronin_print_preview.pdf)

**Comment by postmodern** [comment]
Maybe the animated SVGs need a `animation-play-state: paused;` rule under `print` media layout to disable the SVG animations.

**Comment by s-vamshi** [comment]
@postmodern started working on it but I am facing issues with landing page as you told its taking long to get preview of print even after setting this property animation-play-state: paused; to svg

**Comment by s-vamshi** [comment]
@postmodern do we need to show get involved logo and details in landing page?

**Comment by postmodern** [comment]
> @postmodern do we need to show get involved logos and details in landing page on print?

I thought about hiding them, but maybe it might be useful to show their `href` links as text?

**Comment by s-vamshi** [comment]
@postmodern worked on it but only issue is in landing page svg are not being paused

**Comment by postmodern** [comment]
@s-vamshi maybe we could ignore the issue with the animated SVGs on the front page. As long as the other pages render correctly in Print Preview, that seems acceptable. Maybe someone else can try to solve the unusual issue with the animated SVGs delaying the rendering of the Print Preview.

**Comment by s-vamshi** [comment]
Alright will submit PR by eod
