### ISSUE TITLE
Multiple Broken links on the documentation website

### ISSUE THREAD

**Issue by Smartmind12** [ronin-rb/ronin-rb.github.io#48]
During page navigation there are multiple instances in which an error to the next or linked page arises as shown in the screenshot.

I would be sharing a pull request to mitigate the issue and make the website more efficient.

![Screenshot 2023-10-02 at 7 18 08 PM](https://github.com/ronin-rb/ronin-rb.github.io/assets/91927689/7f04241d-6cff-4d82-a089-ddd010726c83)

**Comment by sahil9001** [comment]
Assign me this issue please, would like to work on it

**Comment by Smartmind12** [comment]
> Assign me this issue please, would like to work on it

@sahil9001 I myself am waiting for it to be assigned to me so that j can work on it . kindly take up another issue!

**Comment by sahil9001** [comment]
No worries, you can take up this one.

**Comment by postmodern** [comment]
@sahil9001 @Smartmind12 unfortunately I am not assigning issues to new contributors. In the past when I have done that people have disappeared and the issues have remained open. Please just submit a PR.

**Comment by postmodern** [comment]
@Smartmind12 also please submit individual PRs to fix or add things, instead of submitting one giant PR that changes and adds multiple things. This makes it easier to review them or request changes.

**Comment by Smartmind12** [comment]
> @Smartmind12 also please submit individual PRs to fix or add things, instead of submitting one giant PR that changes and adds multiple things. This makes it easier to review them or request changes.

Sure got it … will do the needful!

**Comment by postmodern** [comment]
@Smartmind12 can this be closed now? All of your PRs has been merged and I fixed a few broken links as well.

**Comment by Smartmind12** [comment]
> @Smartmind12 can this be closed now? All of your PRs has been merged and I fixed a few broken links as well. Are there more broken links?

Yes I have gone through the same and all links work well ...we can close this issue now!

**Comment by Smartmind12** [comment]
Closing issue #48 as solved by #50 to #56
