### ISSUE TITLE
Change the cursor to pointer 

### ISSUE THREAD

**Issue by CharithaCS** [ronin-rb/ronin-rb.github.io#61]
The cursor needs to turn to a **pointer** when hovering on the dark mode icon in the home page header.
Please review the changes. Thanks :)

Reference:![2023-10-14 16_56_26-Ronin and 5 more pages - Personal - Microsoft​ Edge](https://github.com/ronin-rb/ronin-web/assets/133931559/991fc264-91f7-44cc-868d-2c384871a265)

**Comment by postmodern** [comment]
Is your cursor entirely black? What OS/browser are you using? On Fedora Linux the cursor is black with a white border, so it shows up in dark-mode.

Also, screenshots will not show your cursor by default.

**Comment by NilanjanPramanik** [comment]
Hey I want to work on this issue can i work?

**Comment by postmodern** [comment]
@NilanjanPramanik already submitted a PR, but I'm not sure what the actual issue is here.

**Comment by postmodern** [comment]
Ooooh, I now understand what you mean. The cursor is not changing to the "pointing finger" style of cursor used for links.

**Comment by postmodern** [comment]
Closed by PR #62.

**Comment by CharithaCS** [comment]
> Is your cursor entirely black? What OS/browser are you using? On Chrome on Fedora Linux the cursor is black with a white border, so it shows up in dark-mode.
> 
> Also, screenshots will not show your cursor by default.

I was specifically referring to the pointer finger icon as you mentioned in the other comment.
I apologize for any confusion that has resulted due to this. I should have been more clear about that.
