### ISSUE TITLE
Add "copy to clipboard" JavaScript buttons to the `/install/` commands

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-rb.github.io#76]
All commands on the `/install/` pages should have those dynamic JavaScript "copy to clipboard" buttons. Note, it must only use vanilla JavaScript. No frameworks or NPM libraries allowed.

**Comment by hendriklammers** [comment]
Hi, I would like to contribute and added the "copy to clipboard" button in this PR: https://github.com/ronin-rb/ronin-rb.github.io/pull/77

Please let me know what you think or if any changes are needed.

**Comment by postmodern** [comment]
Implemented by PR #77. Thank you @hendriklammers!
